version: '3.5'

services:
  pongo-internal-auth-api-storage:
    container_name: pongo-internal-auth-api-storage
    image: mysql:5.7
    command: mysqld --sql-mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - ./conf/mysql-5.7/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d ## Executed only the first time the container is created
      - ./storage/mysql-5.7:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret ## Default root username is **root**
      - MYSQL_DATABASE=users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "pongo-internal-auth-api-storage", "-u", "root", "-p", "secret", " | grep 'mysqld is alive' || exit 1"]
      timeout: 20s
      retries: 10
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
