version: '3.5'

services:  
  pongo-keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: pongo-keycloak
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
      - "-Dkeycloak.profile.feature.token_exchange=enabled"
      - "-Dkeycloak.profile.feature.declarative_user_profile=enabled"
    #depends_on:
    #  - pongo-keycloak-database
    #  - pongo-openldap
    environment:
      - KC_PROXY=edge ## put edge with proxmox
      #- KC_HEALTH_ENABLED=true
      #- KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=TRACE
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HOSTNAME_STRICT=false
      # - KC_DB_URL=jdbc:postgresql://keycloak-database:5433/keycloak
      - KC_DB=dev-mem
      #- KC_DB_URL_PORT=5433
      #- KC_DB_URL_HOST=pongo-keycloak-database
      #- KC_DB_URL_DATABASE=pongo-keycloak
      #- KC_DB_USERNAME=keycloak
      #- KC_DB_PASSWORD=password
      #- KC_DB_SCHEMA=
      #- KC_HOSTNAME=localhost:8180 ## Investigate this options
      #- KC_HOSTNAME_PATH=keycloak ## Investigate this options
    ports:
      - 8180:8080 ## HTTP PORT
      - 8143:8443 ## HTTPS PORT
    #links:
    #  - pongo-keycloak-database:pongo-keycloak-database
    #  - pongo-internal-auth-api:pongo-internal-auth-api
    #volumes:
    #  - ./conf/keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    #  - ./conf/keycloak/providers:/opt/keycloak/providers
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}